# Generated by Django 6.0.1 on 2026-01-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dni', models.CharField(blank=True, max_length=8)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celphone', models.CharField(max_length=255)),
                ('participant_type', models.CharField(choices=[('N', 'Notario'), ('A', 'Abogado'), ('T', 'Trabajador notarial'), ('E', 'Estudiante'), ('G', 'Publico en general')], max_length=1)),
                ('notary', models.CharField(blank=True, max_length=255, null=True)),
                ('ruc', models.CharField(blank=True, max_length=11, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('modality', models.CharField(choices=[('P', 'Presencial'), ('V', 'Virtual')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activities', models.ManyToManyField(blank=True, to='storefront.activity')),
            ],
        ),
    ]
