# Generated by Django 6.0.1 on 2026-01-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='receipt',
            field=models.ImageField(blank=True, help_text='Receipt image stored in R2 bucket', null=True, upload_to='receipts/'),
        ),
    ]
