# Generated by Django 6.0.1 on 2026-01-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
