# Generated by Django 6.0.1 on 2026-01-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_companion_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='companion',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
